apiVersion: diagnosis.kubediag.org/v1
kind: OperationSet
metadata:
  name: container-collector
spec:
  adjacencyList:
  - id: 0
    to:
    - 1
  - id: 1
    operation: container-collector
---
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  name: container-collector
spec:
  targetSelector:
    nodeNames:
    - minikube
  operationSet: container-collector
