apiVersion: diagnosis.kubediag.org/v1
kind: OperationSet
metadata:
  name: golang-function
spec:
  adjacencyList:
  - id: 0
    to:
    - 1
  - id: 1
    operation: golang-function
---
apiVersion: diagnosis.kubediag.org/v1
kind: Diagnosis
metadata:
  name: golang-function
spec:
  parameters:
    c: "3"
    d: "4"
  operationSet: golang-function
  nodeName: my-node
