apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: python-function
spec:
  processor:
    function:
      codeSource:
        handler.py: |
          from .hello import hello
          import json

          def handle(event, context):
              data = dict()
              if len(event.body) != 0:
                  data = json.loads(event.body)

              hello()

              result = dict()
              for key in data:
                  result[key] = data[key]
              result["a"] = "1"
              result["b"] = "2"

              json_object = json.dumps(result)
              return {
                  "statusCode": 200,
                  "body": json_object 
              }

        hello.py: |
          def hello():
              print("Hello World")
              
        requirements.txt: |
          requests
      runtime: python3
    timeoutSeconds: 120
